[package]
name = "mdbook-classy"
version = "0.1.1"
authors = ["Doug Bradshaw <dhbradshaw@gmail.com>"]
edition = "2018"
keywords = ["mdbook", "classy", "markdown", "commonmark"]
description = "An mdbook preprocessor for adding html-css classes to markdown.  Enables kramdown style class annotation for markdown paragraphs."
repository = "https://github.com/reviewable/mdbook-classy"
readme = "README.md"
license = "MIT"
exclude = [
    "docs/*",
    "examples/*",
]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
clap = "2.33"
mdbook = "0.4"
pulldown-cmark = "0.7"
pulldown-cmark-to-cmark = "4.0"
serde_json = "1.0"

